export const LANG_OPTIONS = [
  { value: "en-US", label: "English (US)" },
  { value: "en-GB", label: "English (UK)" },
  { value: "en-AU", label: "English (Australia)" },
  { value: "en-CA", label: "English (Canada)" },
  { value: "en-IN", label: "English (India)" },
  { value: "en-NZ", label: "English (New Zealand)" },
  { value: "en-IE", label: "English (Ireland)" },
  { value: "en-SG", label: "English (Singapore)" },
  { value: "en-ZA", label: "English (South Africa)" },
  { value: "en-PH", label: "English (Philippines)" },

  { value: "es-ES", label: "Español (España)" },
  { value: "es-MX", label: "Español (México)" },
  { value: "es-AR", label: "Español (Argentina)" },
  { value: "es-CO", label: "Español (Colombia)" },
  { value: "es-PE", label: "Español (Perú)" },
  { value: "es-VE", label: "Español (Venezuela)" },
  { value: "es-CL", label: "Español (Chile)" },
  { value: "es-US", label: "Español (USA)" },
  { value: "es-EC", label: "Español (Ecuador)" },
  { value: "es-BO", label: "Español (Bolivia)" },
  { value: "es-DO", label: "Español (Rep. Dominicana)" },
  { value: "es-GT", label: "Español (Guatemala)" },
  { value: "es-HN", label: "Español (Honduras)" },
  { value: "es-NI", label: "Español (Nicaragua)" },
  { value: "es-PA", label: "Español (Panamá)" },
  { value: "es-PR", label: "Español (Puerto Rico)" },
  { value: "es-PY", label: "Español (Paraguay)" },
  { value: "es-SV", label: "Español (El Salvador)" },
  { value: "es-UY", label: "Español (Uruguay)" },
  { value: "es-CR", label: "Español (Costa Rica)" },

  { value: "zh-CN", label: "中文 (简体)" },
  { value: "zh-TW", label: "中文 (繁體)" },
  { value: "hi-IN", label: "हिन्दी (India)" },
  { value: "fr-FR", label: "Français (France)" },
  { value: "fr-CA", label: "Français (Canada)" },
  { value: "fr-BE", label: "Français (Belgique)" },
  { value: "fr-CH", label: "Français (Suisse)" },
  { value: "fr-LU", label: "Français (Luxembourg)" },
  { value: "pt-BR", label: "Português (Brasil)" },
  { value: "pt-PT", label: "Português (Portugal)" },
  { value: "pt-AO", label: "Português (Angola)" },
  { value: "pt-MZ", label: "Português (Moçambique)" },
  { value: "de-DE", label: "Deutsch (Deutschland)" },
  { value: "de-AT", label: "Deutsch (Österreich)" },
  { value: "de-CH", label: "Deutsch (Schweiz)" },
  { value: "de-LU", label: "Deutsch (Luxemburg)" },
  { value: "de-LI", label: "Deutsch (Liechtenstein)" },
  { value: "ja-JP", label: "日本語 (日本)" },
  { value: "ko-KR", label: "한국어 (대한민국)" },
  { value: "it-IT", label: "Italiano (Italia)" },
  { value: "it-CH", label: "Italiano (Svizzera)" },
  { value: "ru-RU", label: "Русский (Россия)" },
  { value: "vi-VN", label: "Tiếng Việt (Việt Nam)" },
  { value: "tr-TR", label: "Türkçe (Türkiye)" },
  { value: "id-ID", label: "Bahasa Indonesia" },
  { value: "pl-PL", label: "Polski (Polska)" },
  { value: "th-TH", label: "ไทย (ประเทศไทย)" },
];
